// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPaGoBQlPZwxdO3QDA7JGUr-jZUviLCyM',
    appId: '1:275982759255:web:fb0022310f0e5534c43a12',
    messagingSenderId: '275982759255',
    projectId: 'smartwatch-university-project',
    authDomain: 'smartwatch-university-project.firebaseapp.com',
    storageBucket: 'smartwatch-university-project.firebasestorage.app',
    measurementId: 'G-GXEN01YGRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP_M_H1PhWzxRjiO5p5PGJNTicHiJFxqY',
    appId: '1:275982759255:android:570861e8e88788bbc43a12',
    messagingSenderId: '275982759255',
    projectId: 'smartwatch-university-project',
    storageBucket: 'smartwatch-university-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0Xrmq5gHkTtwfQzmfk6022rrETrnPa5M',
    appId: '1:275982759255:ios:8b51d4daae4c6066c43a12',
    messagingSenderId: '275982759255',
    projectId: 'smartwatch-university-project',
    storageBucket: 'smartwatch-university-project.firebasestorage.app',
    iosBundleId: 'com.example.smartWatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0Xrmq5gHkTtwfQzmfk6022rrETrnPa5M',
    appId: '1:275982759255:ios:8b51d4daae4c6066c43a12',
    messagingSenderId: '275982759255',
    projectId: 'smartwatch-university-project',
    storageBucket: 'smartwatch-university-project.firebasestorage.app',
    iosBundleId: 'com.example.smartWatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPaGoBQlPZwxdO3QDA7JGUr-jZUviLCyM',
    appId: '1:275982759255:web:bbafb2a60f9e4601c43a12',
    messagingSenderId: '275982759255',
    projectId: 'smartwatch-university-project',
    authDomain: 'smartwatch-university-project.firebaseapp.com',
    storageBucket: 'smartwatch-university-project.firebasestorage.app',
    measurementId: 'G-EVVJQZBXKE',
  );
}
